### ISSUE TITLE
Prepare release 2.8.0

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/hatyan#110]
TODO:
- [x] https://github.com/Deltares/hatyan/issues/106
- [x] #113
- [x] #115
- [x] #119
- [x] https://github.com/Deltares/hatyan/issues/117
- [x] #121
- [x] #124
- [x] https://github.com/Deltares/hatyan/issues/126
- [x] https://github.com/Deltares/hatyan/issues/128
- [x] https://github.com/Deltares/hatyan/issues/137
- [x] https://github.com/Deltares/hatyan/issues/93, simplifies example scripts by not having to pass metadata manually
- [x] add L9PFM and Q1 to xfac0 list in all example files
- [x] https://github.com/Deltares/hatyan/issues/104
- [x] https://github.com/Deltares/hatyan/issues/151
- [x] https://github.com/Deltares/hatyan/issues/154
- [x] https://github.com/Deltares/hatyan/issues/150
- [x] https://github.com/Deltares/hatyan/issues/146
- [x] https://github.com/Deltares/hatyan/issues/132
- [x] https://github.com/Deltares/hatyan/issues/159
- [x] https://github.com/Deltares/hatyan/issues/153
- [x] `python -m hatyan -h` does not work anymore?
- [x] https://github.com/Deltares/hatyan/issues/163
- [x] https://github.com/Deltares/hatyan/issues/165
- [x] #168
- [x] https://github.com/Deltares/hatyan/issues/170
- [x] https://github.com/Deltares/hatyan/issues/172
- [x] https://github.com/Deltares/hatyan/issues/144 (discuss issues with JR/AB)
- [x] https://github.com/Deltares/hatyan/issues/176
- [x] https://github.com/Deltares/hatyan/issues/179
- [x] https://github.com/Deltares/hatyan/issues/180
- [x] #183
- [x] https://github.com/Deltares/hatyan/issues/185
- [x] uncomment py312 classifier in toml file
- [x] https://github.com/Deltares/hatyan/issues/189
- [x] #166
- [x] remove `.gitattributes`?
- [x] https://github.com/Deltares/hatyan/issues/194
- [x] https://github.com/Deltares/hatyan/issues/173
- [x] https://github.com/Deltares/hatyan/issues/198
- [x] https://github.com/Deltares/hatyan/issues/212
- [x] #207
- [x] during release: https://github.com/Deltares/dfm_tools/issues/732
- [x] https://github.com/Deltares/hatyan/issues/139 (discuss with JR/AB)
- [x] #217
- [x] update readme: remove ddl part an kwk part
- [x] https://github.com/Deltares/hatyan/issues/214
- [x] https://github.com/Deltares/hatyan/issues/215
- [x] https://github.com/Deltares/hatyan/issues/220
- [x] https://github.com/Deltares/hatyan/issues/227
- [x] https://github.com/Deltares/hatyan/issues/226
- [x] https://github.com/Deltares/hatyan/issues/230
- [x] #184
- [x] #233
- [x] https://github.com/Deltares/hatyan/issues/177
- [x] https://github.com/Deltares/hatyan/issues/98
- [x] #237
- [x] restore script header in https://github.com/Deltares/hatyan/blob/main/tests/examples/predictie_2019_19Ycomp4Ydia_VLISSGN.py
- [x] https://github.com/Deltares/hatyan/issues/241
- [x] #243
- [x] https://github.com/Deltares/hatyan/issues/247
- [x] https://github.com/Deltares/hatyan/issues/249
- [x] remove docs/hatyan folder, this is not used anymore.
- [x] https://github.com/Deltares/hatyan/issues/221
- [x] #252
- [x] #254
- [x] https://github.com/Deltares/hatyan/issues/238
- [x] https://github.com/Deltares/hatyan/issues/216
- [x] check timeout acceptance: numbering_extremes and spatial_plots (after adding dfmt.plot_coastlines)
- [x] update testbank, jupyter notebook, example scripts
- [x] #261
- [x] #264
- [x] #266
- [x] https://github.com/Deltares/hatyan/issues/263
- [x] https://github.com/Deltares/hatyan/issues/269
- [x] https://github.com/Deltares/hatyan/issues/271
- [x] https://github.com/Deltares/hatyan/issues/274
- [x] https://github.com/Deltares/hatyan/issues/130
- [x] #276
- [x] #278
- [x] #280
- [x] #283
- [x] #282
- [x] #286
- [x] add prints of comp and ts to example notebook (in separate blocks)
- [x] #291
- [x] https://github.com/Deltares/hatyan/issues/294
- [x] https://github.com/Deltares/hatyan/issues/289
- [x] https://github.com/Deltares/hatyan/issues/287
- [x] shorter variable names in example scripts to make it less messy
- [x] https://github.com/Deltares/hatyan/issues/297
- [x] https://github.com/Deltares/hatyan/issues/299
- [x] https://github.com/Deltares/hatyan/issues/225
- [x] https://github.com/Deltares/hatyan/issues/97
- [x] run entire testbank and check acceptance test output
- [x] update whatsnew

Overview of user impact of finished todo's:
- https://github.com/Deltares/hatyan/blob/main/docs/whats-new.md
- https://github.com/Deltares/hatyan/pull/114
- https://github.com/Deltares/hatyan/pull/116
- https://github.com/Deltares/hatyan/pull/127
- https://github.com/Deltares/hatyan/pull/131
- https://github.com/Deltares/hatyan/pull/143
- https://github.com/Deltares/hatyan/pull/175 (including support for old hatyan1 files without analysis settings)
- https://github.com/Deltares/hatyan/pull/196 (this change makes it impossible to read haytan2<=2.7.0 component files since they do not contain STAT/PERD metadata lines, an error is raised)
- https://github.com/Deltares/hatyan/pull/218 (prevent prediction with different settings than in components metadata and prevent non-standard nodalfactors/fu_alltimes/source in component file)
- https://github.com/Deltares/hatyan/pull/223 (deprecated `hatyan.write_tsdia_HWLW()`)
- https://github.com/Deltares/hatyan/pull/229 (makes `hatyan` commmand available via command line directly, instead of via `python -m hatyan`)
- https://github.com/Deltares/hatyan/pull/236 (prevented most of the prints, now to be enabled with logging module)
- https://github.com/Deltares/hatyan/pull/242 (improved documentation on github)
- https://github.com/Deltares/hatyan/pull/260 (removed station/vertref/tzone_hr arguments for hatyan.write_tsnetcdf(), comes from timeseries dataframes now, tzone was removed in https://github.com/Deltares/hatyan/pull/258)
- https://github.com/Deltares/hatyan/pull/265 (dropped "ts" from all read/write timeseries function names)
- https://github.com/Deltares/hatyan/pull/268 (hatyan.prediction() does not accepts settings anymore, they are derived from the components dataframe now, this prevents accidental mistakes)
- https://github.com/Deltares/hatyan/pull/288 (prediction timestep now only accepts frequency string like `"10min"`, not `10` anymore)
- https://github.com/Deltares/hatyan/pull/292 (renamed `CS_comps` argument for `hatyan.prediction()` to lowercase)
- overview by comparing the example script: [old (2.7.0)](https://github.com/Deltares/hatyan/blob/v2.7.0/tests/examples/predictie_2019_19Ycomp4Ydia_VLISSGN_interactive.py) vs. [new/simplified (main)](https://github.com/Deltares/hatyan/blob/main/tests/examples/predictie_2019_19Ycomp4Ydia_VLISSGN.py)
- improved module documentation at [deltares.github.io](https://deltares.github.io/hatyan/modules.html)

FEWS HWLW numbering impact:
- removed station/vertref/tzone_hr arguments for hatyan.write_tsnetcdf(): https://github.com/Deltares/hatyan/pull/258 and 
https://github.com/Deltares/hatyan/pull/260
- renamed `hatyan.writets_netcdf()` to `hatyan.write_netcdf()` https://github.com/Deltares/hatyan/pull/265

After release:
- [ ] build method was updated, check if data was packaged in wheel (pip install in clean env)
- [ ] zenodo published?
- [ ] check budget/spendings
- [ ] test/adjust kenmerkendewaarden scripts
- [ ] update gtsm scripts
