### ISSUE TITLE
Update DDL

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/hatyan#187]
**Todo hatyan/ddlpy**
- [x] #200
- [x] https://github.com/openearth/ddlpy/issues/20
- [x] #201
- [x] https://github.com/openearth/ddlpy/issues/29
- [x] https://github.com/openearth/ddlpy/issues/26
- [x] https://github.com/Deltares/hatyan/issues/203
- [x] https://github.com/openearth/ddlpy/issues/27
- [x] https://github.com/openearth/ddlpy/issues/24
- [x] https://github.com/openearth/ddlpy/issues/39
- [x] https://github.com/openearth/ddlpy/issues/42
- [x] https://github.com/openearth/ddlpy/issues/38
- [x] https://github.com/openearth/ddlpy/issues/21
- [x] ddlpy: add more features from getonlinedata.py
- [ ] https://github.com/Deltares/hatyan/issues/207

Follow up issue in kenmerkendewaarden repository: https://github.com/Deltares-research/kenmerkendewaarden/issues/4

**Comment by veenstrajelmer** [comment]
This issue can be closed since all issues are ddl/data related. Haytan does not have ddl functions anymore, since it uses ddlpy now. Also, the data related issues are mainly relevant for the kenmerkende waarden project, so these are moved to Follow up issue in kenmerkendewaarden repository: https://github.com/Deltares-research/kenmerkendewaarden/issues/4
